const questions = [
  {
    id: 0,
    q: "le tracteur",
    translation: "the tractor",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 1,
    q: "la chaise",
    translation: "the chair",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 2,
    q: "le chat",
    translation: "the cat",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 3,
    q: "la carotte",
    translation: "the carrot",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 4,
    q: "la table",
    translation: "the table",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 5,
    q: "jaune",
    translation: "yellow",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 6,
    q: "le tee-shirt",
    translation: "the t-shirt",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 7,
    q: "la voiture",
    translation: "car",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 8,
    q: "la vache",
    translation: "cow",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 9,
    q: "la pendule",
    translation: "the clock",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 10,
    q: "le chocolat",
    translation: "the chocolate",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 11,
    q: "le fromage",
    translation: "the cheese",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 12,
    q: "la fleur",
    translation: "the flower",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 13,
    q: "le canard",
    translation: "the duck",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 14,
    q: "le chien",
    translation: "the dog",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 15,
    q: "la maison",
    translation: "the house",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 16,
    q: "vert",
    translation: "green",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 17,
    q: "la fille",
    translation: "the girl",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 18,
    q: "le crayon",
    translation: "pencil",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 19,
    q: "l'orange",
    translation: "the orange",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 20,
    q: "la souris",
    translation: "the mouse",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 21,
    q: "la glace",
    translation: "the ice cream",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 22,
    q: "les chaussures",
    translation: "the shoes",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 23,
    q: "rouge",
    translation: "red",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 24,
    q: "le lapin",
    translation: "rabbit",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 25,
    q: "l'avion",
    translation: "the plane",
    options: ["yes", "no"],
    answer: 0,
  },
]

// {
//   id: [],
//   q: "exampleToCopy",
//   translation: "exampleToCopy",
//   options: ["yes", "no"],
//   answer: 0,
// },